# Generated by Django 3.2.18 on 2023-03-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
