# Generated by Django 3.2.18 on 2023-03-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20230329_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='number',
        ),
        migrations.RemoveField(
            model_name='place',
            name='placeId',
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
